
import React, { useState } from 'react';
import { QrCode, Copy, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';

type QRCodeGeneratorProps = {
  studentName: string;
  amount: number;
  purpose: string;
};

const QRCodeGenerator: React.FC<QRCodeGeneratorProps> = ({ 
  studentName, 
  amount, 
  purpose 
}) => {
  const [copied, setCopied] = useState(false);

  // In a real app, this would be generated by Razorpay or another payment gateway
  const qrImageUrl = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=upi://pay?pa=school@upi&pn=SchoolFees&am=${amount}&cu=INR&tn=${encodeURIComponent(`${purpose} for ${studentName}`)}`;

  const copyPaymentLink = () => {
    // In a real app, this would be a proper payment link
    const paymentLink = `upi://pay?pa=school@upi&pn=SchoolFees&am=${amount}&cu=INR&tn=${encodeURIComponent(`${purpose} for ${studentName}`)}`;
    navigator.clipboard.writeText(paymentLink);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" className="flex items-center gap-2">
          <QrCode className="h-4 w-4" />
          Generate QR Code
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Payment QR Code</DialogTitle>
        </DialogHeader>
        <div className="flex flex-col items-center gap-4 py-4">
          <div className="text-center mb-2">
            <p className="font-medium">{studentName}</p>
            <p className="text-sm text-muted-foreground">{purpose}</p>
            <p className="text-xl font-bold mt-1">₹{amount.toLocaleString()}</p>
          </div>
          
          <div className="border rounded-md p-2 bg-white">
            <img 
              src={qrImageUrl} 
              alt={`Payment QR for ${studentName}`}
              className="w-48 h-48"
            />
          </div>
          
          <div className="flex justify-center gap-2 w-full">
            <Button 
              variant="outline" 
              className="flex items-center gap-1" 
              onClick={copyPaymentLink}
            >
              {copied ? (
                <>
                  <Check className="h-4 w-4" />
                  Copied
                </>
              ) : (
                <>
                  <Copy className="h-4 w-4" />
                  Copy UPI Link
                </>
              )}
            </Button>
            <Button>Mark as Paid</Button>
          </div>
          
          <p className="text-xs text-center text-muted-foreground mt-2">
            Parents can scan this QR code to pay the exact amount.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default QRCodeGenerator;
